version: "3.8"
services:
  user-service:
    build: ./user-service
    ports:
    #  - "8722:8722"
      - "81:81"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/user:/logs
      - /tmp/logs/user/csp:/root/logs
  glycemia-service:
    build: ./glycemia-service
    ports:
      - "8721:8721"
      - "82:82"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/glycemia:/logs
      - /tmp/logs/glycemia/csp:/root/logs
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
      - "8719:8719"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/gateway:/logs
      - /tmp/logs/gateway/csp:/root/logs
  interact-service:
    build: ./interact-service
    ports:
      - "85:85"
      - "8724:8724"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/oa-service:/logs
      - /tmp/logs/oa-service/csp:/root/logs
  oa-service:
    build: ./oa-service
    ports:
      - "84:84"
      - "8723:8723"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/oa-service:/logs
      - /tmp/logs/oa-service/csp:/root/logs
  exercise-service:
    build: ./exercise-service
    ports:
    #  - "8720:8720"
      - "83:83"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/exercise:/logs
      - /tmp/logs/exercise/csp:/root/logs
