version: "3.8"
services:
  # NOTICE: AOF and RDB needs to be at /tmp/redis/data
  redis:
    image: redis:6.2.14
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --daemonize no
    volumes:
      - /tmp/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /tmp/redis/data:/data
    ports:
      - 6379:6379
  # NOTICE: 4 ENV variables are required for the following services,you can define them in web-variables.env
  mysql:
    image: mysql:5.7.43
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  # NOTICE: you should deploy the 1st website at /tmp/nginx/html/admin,the 2nd at /tmp/nginx/html/doctor
  nginx:
    image: nginx:latest
    ports:
      - "5672:5672"
      - "5173:5173"
      - "8858:8858"
    volumes:
      - /tmp/nginx/conf:/etc/nginx
      - /tmp/nginx/logs:/var/log/nginx
      - /tmp/nginx/html:/usr/share/nginx/html
  user-service:
    build: ./user-service
    ports:
    #  - "8722:8722"
      - "81:81"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/user:/logs
      - /tmp/logs/user/csp:/root/logs
  glycemia-service:
    build: ./glycemia-service
    ports:
      - "8721:8721"
      - "82:82"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/glycemia:/logs
      - /tmp/logs/glycemia/csp:/root/logs
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
      - "8719:8719"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/gateway:/logs
      - /tmp/logs/gateway/csp:/root/logs
  interact-service:
    build: ./interact-service
    ports:
      - "85:85"
      - "8724:8724"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/oa-service:/logs
      - /tmp/logs/oa-service/csp:/root/logs
  oa-service:
    build: ./oa-service
    ports:
      - "84:84"
      - "8723:8723"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/oa-service:/logs
      - /tmp/logs/oa-service/csp:/root/logs
  exercise-service:
    build: ./exercise-service
    ports:
    #  - "8720:8720"
      - "83:83"
    env_file:
      - ./web-variables.env
    volumes:
      - /tmp/logs/exercise:/logs
      - /tmp/logs/exercise/csp:/root/logs
