server:
  port: 10083
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    location: http://${spring.cloud.nacos.server-addr}/nacos/v1/cs/configs?group=SECURITY&tenant=${spring.cloud.nacos.discovery.namespace}&dataId=security.xml
  jackson:
    default-property-inclusion: non-null
    #type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:edu/tongji/backend/mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    table-prefix: tbl_
    id-type: auto
management:
  metrics:
    tags:
      application: jmx-exercise-service
feign:
  client:
    config:
      defaultTimeout: 600000
      readTimeout: 600000
