logging:
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c [%thread] %msg %n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c [%thread] %msg %n"
  level:
    edu:
      tongji: info
  file:
    path: "/log/springboot/"
server:
  port: 81
  tomcat:
    accesslog:
      buffered: true
      directory: /logs/springboot/
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:

  profiles:
    active: pro
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        prefetch: 1
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non-null
    serialization:
        FAIL_ON_EMPTY_BEANS: false
    #type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:edu/tongji/backend/mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    table-prefix: tbl_
    id-type: auto

