name: Glycemia SE Doc
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  doc-generate:
    runs-on: ubuntu-latest
    environment: SERVER_WITH_PUBLIC_IP
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Create docs/
        run: mkdir docs
      - name: Create docs/
        run: chmod 777 docs
      - name: Generate doc under docs/
        run: javadoc -d docs -sourcepath exercise-service/src/main/java/:oa-service/src/main/java/:glycemia-service/src/main/java/:user-service/src/main/java/:gateway/src/main/java/:common-api/src/main/java/ -subpackages edu.tongji.backend -Xdoclint:none
        continue-on-error: true
      - name: Upload Documents as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Javadoc Documents
          path: |
            docs/


 
