name: Glycemia SE Doc
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
jobs:
  doc-generate:
    runs-on: ubuntu-latest
    environment: SERVER_WITH_PUBLIC_IP
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Create docs/
        run: mkdir docs
      - name: Generate doc under docs/
        run: javadoc -d docs -sourcepath exercise-service/src/main/java/:oa-service/src/main/java/:glycemia-service/src/main/java/:user-service/src/main/java/:gateway/src/main/java/:common-api/src/main/java/ -subpackages edu.tongji.backend -Xdoclint:none
      - name: Upload Documents as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Javadoc Documents
          path: |
            docs/


 
