name: Docker Image Sync
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker run Redis and Nginx images
        run: |
          docker pull redis:6.2.14
          docker pull nginx:latest
          docker pull mysql:5.7.43
      - name: Tar all images
        run: |
          docker save -o redis.tar redis:6.2.14
          docker save -o nginx.tar nginx:latest
          docker save -o mysql.tar mysql:5.7.43
      - name: Upload images
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: |
            redis.tar
            nginx.tar
            mysql.tar